site_name: RAG Charts
repo_url: https://github.com/kbhatiya999/rag-charts
repo_name: rag-charts

theme:
  name: material
  features:
    - content.code.copy
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.snippets

nav:
  - Home: index.md
  - Podman Desktop:
    - "1. Installation": podman-desktop/1-installation.md
    - "2. Setup Cluster": podman-desktop/2-setup-cluster.md
