site_name: RAG Charts
repo_url: https://github.com/kbhatiya999/rag-charts
repo_name: rag-charts

theme:
  name: material
  features:
    - content.code.copy
  palette:
    - scheme: default
      primary: blue grey
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue grey
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.snippets

nav:
  - Home: index.md
  - Local Cluster with Podman Desktop: podman-desktop.md
